// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/screens/home_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:app/models/models.dart' as _i2;
import 'package:app/providers/providers.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i3.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.User get authUser => (super.noSuchMethod(
        Invocation.getter(#authUser),
        returnValue: _FakeUser_0(
          this,
          Invocation.getter(#authUser),
        ),
      ) as _i2.User);

  @override
  _i4.Future<_i3.TwoFactorChallenge?> login({
    required String? host,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #host: host,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i3.TwoFactorChallenge?>.value(),
      ) as _i4.Future<_i3.TwoFactorChallenge?>);

  @override
  _i4.Future<void> completeTwoFactorChallenge({
    required String? loginToken,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTwoFactorChallenge,
          [],
          {
            #loginToken: loginToken,
            #code: code,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loginWithOneTimeToken({
    required String? host,
    required String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithOneTimeToken,
          [],
          {
            #host: host,
            #token: token,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setAuthUser(_i2.User? user) => super.noSuchMethod(
        Invocation.method(
          #setAuthUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.User?> tryGetAuthUser() => (super.noSuchMethod(
        Invocation.method(
          #tryGetAuthUser,
          [],
        ),
        returnValue: _i4.Future<_i2.User?>.value(),
      ) as _i4.Future<_i2.User?>);

  @override
  _i4.Future<_i2.User> refreshAuthUser() => (super.noSuchMethod(
        Invocation.method(
          #refreshAuthUser,
          [],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #refreshAuthUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OverviewProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockOverviewProvider extends _i1.Mock implements _i3.OverviewProvider {
  MockOverviewProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Playable<dynamic>> get mostPlayedSongs => (super.noSuchMethod(
        Invocation.getter(#mostPlayedSongs),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  List<_i2.Playable<dynamic>> get recentlyAddedSongs => (super.noSuchMethod(
        Invocation.getter(#recentlyAddedSongs),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  List<_i2.Playable<dynamic>> get recentlyPlayedSongs => (super.noSuchMethod(
        Invocation.getter(#recentlyPlayedSongs),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  List<_i2.Playable<dynamic>> get leastPlayedSongs => (super.noSuchMethod(
        Invocation.getter(#leastPlayedSongs),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  List<_i2.Playable<dynamic>> get randomSongs => (super.noSuchMethod(
        Invocation.getter(#randomSongs),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  List<_i2.Playable<dynamic>> get similarSongs => (super.noSuchMethod(
        Invocation.getter(#similarSongs),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  List<_i2.Album> get mostPlayedAlbums => (super.noSuchMethod(
        Invocation.getter(#mostPlayedAlbums),
        returnValue: <_i2.Album>[],
      ) as List<_i2.Album>);

  @override
  List<_i2.Album> get recentlyAddedAlbums => (super.noSuchMethod(
        Invocation.getter(#recentlyAddedAlbums),
        returnValue: <_i2.Album>[],
      ) as List<_i2.Album>);

  @override
  List<_i2.Album> get randomAlbums => (super.noSuchMethod(
        Invocation.getter(#randomAlbums),
        returnValue: <_i2.Album>[],
      ) as List<_i2.Album>);

  @override
  List<_i2.Artist> get mostPlayedArtists => (super.noSuchMethod(
        Invocation.getter(#mostPlayedArtists),
        returnValue: <_i2.Artist>[],
      ) as List<_i2.Artist>);

  @override
  List<_i2.Artist> get recentlyAddedArtists => (super.noSuchMethod(
        Invocation.getter(#recentlyAddedArtists),
        returnValue: <_i2.Artist>[],
      ) as List<_i2.Artist>);

  @override
  List<_i2.Artist> get randomArtists => (super.noSuchMethod(
        Invocation.getter(#randomArtists),
        returnValue: <_i2.Artist>[],
      ) as List<_i2.Artist>);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RecentlyPlayedProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecentlyPlayedProvider extends _i1.Mock
    implements _i3.RecentlyPlayedProvider {
  MockRecentlyPlayedProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Playable<dynamic>> get playables => (super.noSuchMethod(
        Invocation.getter(#playables),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  set playables(List<_i2.Playable<dynamic>>? _playables) => super.noSuchMethod(
        Invocation.setter(
          #playables,
          _playables,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<List<_i2.Playable<dynamic>>> fetch() => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Playable<dynamic>>>.value(
            <_i2.Playable<dynamic>>[]),
      ) as _i4.Future<List<_i2.Playable<dynamic>>>);

  @override
  void seed(List<_i2.Playable<dynamic>>? items) => super.noSuchMethod(
        Invocation.method(
          #seed,
          [items],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i2.Playable<dynamic>? playable) => super.noSuchMethod(
        Invocation.method(
          #add,
          [playable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
