// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/screens/profile_action_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:app/audio_handler.dart' as _i6;
import 'package:app/models/models.dart' as _i5;
import 'package:app/providers/providers.dart' as _i2;
import 'package:audio_service/audio_service.dart' as _i7;
import 'package:just_audio/just_audio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:rxdart/rxdart.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDownloadProvider_0 extends _i1.SmartFake
    implements _i2.DownloadProvider {
  _FakeDownloadProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayableProvider_1 extends _i1.SmartFake
    implements _i2.PlayableProvider {
  _FakePlayableProvider_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioPlayer_3 extends _i1.SmartFake implements _i3.AudioPlayer {
  _FakeAudioPlayer_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBehaviorSubject_4<T> extends _i1.SmartFake
    implements _i4.BehaviorSubject<T> {
  _FakeBehaviorSubject_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePublishSubject_5<T> extends _i1.SmartFake
    implements _i4.PublishSubject<T> {
  _FakePublishSubject_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_6<T> extends _i1.SmartFake
    implements _i4.ValueStream<T> {
  _FakeValueStream_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_7 extends _i1.SmartFake implements _i5.User {
  _FakeUser_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KoelAudioHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockKoelAudioHandler extends _i1.Mock implements _i6.KoelAudioHandler {
  MockKoelAudioHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DownloadProvider get downloadProvider => (super.noSuchMethod(
        Invocation.getter(#downloadProvider),
        returnValue: _FakeDownloadProvider_0(
          this,
          Invocation.getter(#downloadProvider),
        ),
      ) as _i2.DownloadProvider);

  @override
  _i2.PlayableProvider get playableProvider => (super.noSuchMethod(
        Invocation.getter(#playableProvider),
        returnValue: _FakePlayableProvider_1(
          this,
          Invocation.getter(#playableProvider),
        ),
      ) as _i2.PlayableProvider);

  @override
  _i7.AudioServiceRepeatMode get repeatMode => (super.noSuchMethod(
        Invocation.getter(#repeatMode),
        returnValue: _i7.AudioServiceRepeatMode.none,
      ) as _i7.AudioServiceRepeatMode);

  @override
  Duration get sourceLoadTimeout => (super.noSuchMethod(
        Invocation.getter(#sourceLoadTimeout),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#sourceLoadTimeout),
        ),
      ) as Duration);

  @override
  _i3.AudioPlayer get player => (super.noSuchMethod(
        Invocation.getter(#player),
        returnValue: _FakeAudioPlayer_3(
          this,
          Invocation.getter(#player),
        ),
      ) as _i3.AudioPlayer);

  @override
  bool get isRadioMode => (super.noSuchMethod(
        Invocation.getter(#isRadioMode),
        returnValue: false,
      ) as bool);

  @override
  int get currentQueueIndex => (super.noSuchMethod(
        Invocation.getter(#currentQueueIndex),
        returnValue: 0,
      ) as int);

  @override
  set downloadProvider(_i2.DownloadProvider? _downloadProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #downloadProvider,
          _downloadProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set playableProvider(_i2.PlayableProvider? _playableProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #playableProvider,
          _playableProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set repeatMode(_i7.AudioServiceRepeatMode? _repeatMode) => super.noSuchMethod(
        Invocation.setter(
          #repeatMode,
          _repeatMode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.BehaviorSubject<_i7.PlaybackState> get playbackState =>
      (super.noSuchMethod(
        Invocation.getter(#playbackState),
        returnValue: _FakeBehaviorSubject_4<_i7.PlaybackState>(
          this,
          Invocation.getter(#playbackState),
        ),
      ) as _i4.BehaviorSubject<_i7.PlaybackState>);

  @override
  _i4.BehaviorSubject<List<_i7.MediaItem>> get queue => (super.noSuchMethod(
        Invocation.getter(#queue),
        returnValue: _FakeBehaviorSubject_4<List<_i7.MediaItem>>(
          this,
          Invocation.getter(#queue),
        ),
      ) as _i4.BehaviorSubject<List<_i7.MediaItem>>);

  @override
  _i4.BehaviorSubject<String> get queueTitle => (super.noSuchMethod(
        Invocation.getter(#queueTitle),
        returnValue: _FakeBehaviorSubject_4<String>(
          this,
          Invocation.getter(#queueTitle),
        ),
      ) as _i4.BehaviorSubject<String>);

  @override
  _i4.BehaviorSubject<_i7.MediaItem?> get mediaItem => (super.noSuchMethod(
        Invocation.getter(#mediaItem),
        returnValue: _FakeBehaviorSubject_4<_i7.MediaItem?>(
          this,
          Invocation.getter(#mediaItem),
        ),
      ) as _i4.BehaviorSubject<_i7.MediaItem?>);

  @override
  _i4.BehaviorSubject<_i7.AndroidPlaybackInfo> get androidPlaybackInfo =>
      (super.noSuchMethod(
        Invocation.getter(#androidPlaybackInfo),
        returnValue: _FakeBehaviorSubject_4<_i7.AndroidPlaybackInfo>(
          this,
          Invocation.getter(#androidPlaybackInfo),
        ),
      ) as _i4.BehaviorSubject<_i7.AndroidPlaybackInfo>);

  @override
  _i4.BehaviorSubject<_i7.RatingStyle> get ratingStyle => (super.noSuchMethod(
        Invocation.getter(#ratingStyle),
        returnValue: _FakeBehaviorSubject_4<_i7.RatingStyle>(
          this,
          Invocation.getter(#ratingStyle),
        ),
      ) as _i4.BehaviorSubject<_i7.RatingStyle>);

  @override
  _i4.PublishSubject<dynamic> get customEvent => (super.noSuchMethod(
        Invocation.getter(#customEvent),
        returnValue: _FakePublishSubject_5<dynamic>(
          this,
          Invocation.getter(#customEvent),
        ),
      ) as _i4.PublishSubject<dynamic>);

  @override
  _i4.BehaviorSubject<dynamic> get customState => (super.noSuchMethod(
        Invocation.getter(#customState),
        returnValue: _FakeBehaviorSubject_4<dynamic>(
          this,
          Invocation.getter(#customState),
        ),
      ) as _i4.BehaviorSubject<dynamic>);

  @override
  dynamic init({
    required _i2.PlayableProvider? playableProvider,
    required _i2.DownloadProvider? downloadProvider,
  }) =>
      super.noSuchMethod(Invocation.method(
        #init,
        [],
        {
          #playableProvider: playableProvider,
          #downloadProvider: downloadProvider,
        },
      ));

  @override
  void enterRadioMode(_i3.AudioPlayer? radioPlayer) => super.noSuchMethod(
        Invocation.method(
          #enterRadioMode,
          [radioPlayer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void exitRadioMode() => super.noSuchMethod(
        Invocation.method(
          #exitRadioMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateRadioPlaybackState({
    required bool? playing,
    required _i7.AudioProcessingState? processingState,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateRadioPlaybackState,
          [],
          {
            #playing: playing,
            #processingState: processingState,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  num? getPlaybackPositionFromState(String? playableId) =>
      (super.noSuchMethod(Invocation.method(
        #getPlaybackPositionFromState,
        [playableId],
      )) as num?);

  @override
  void setPlaybackPositionToState(
    String? playableId,
    num? position,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setPlaybackPositionToState,
          [
            playableId,
            position,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> queueAndPlay(_i5.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueAndPlay,
          [playable],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> maybeQueueAndPlay(
    _i5.Playable<dynamic>? playable, {
    dynamic position = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #maybeQueueAndPlay,
          [playable],
          {#position: position},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> queueAfterCurrent(_i5.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueAfterCurrent,
          [playable],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playOrPause() => (super.noSuchMethod(
        Invocation.method(
          #playOrPause,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> skipToNext() => (super.noSuchMethod(
        Invocation.method(
          #skipToNext,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> skipToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #skipToPrevious,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> queued(_i5.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #queued,
          [playable],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> removeQueueItemAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeQueueItemAt,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void moveQueueItem(
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #moveQueueItem,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> clearQueue() => (super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setVolume(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> replaceQueue(
    List<_i5.Playable<dynamic>>? playables, {
    bool? shuffle = false,
    bool? autoPlay = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceQueue,
          [playables],
          {
            #shuffle: shuffle,
            #autoPlay: autoPlay,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i7.AudioServiceRepeatMode> rotateRepeatMode() =>
      (super.noSuchMethod(
        Invocation.method(
          #rotateRepeatMode,
          [],
        ),
        returnValue: _i8.Future<_i7.AudioServiceRepeatMode>.value(
            _i7.AudioServiceRepeatMode.none),
      ) as _i8.Future<_i7.AudioServiceRepeatMode>);

  @override
  _i8.Future<void> setRepeatMode(_i7.AudioServiceRepeatMode? repeatMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRepeatMode,
          [repeatMode],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cleanUpUponLogout() => (super.noSuchMethod(
        Invocation.method(
          #cleanUpUponLogout,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> queueToBottom(_i5.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueToBottom,
          [playable],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeFromQueue(_i5.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromQueue,
          [playable],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> prepare() => (super.noSuchMethod(
        Invocation.method(
          #prepare,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> prepareFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromMediaId,
          [
            mediaId,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> prepareFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromSearch,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> prepareFromUri(
    Uri? uri, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromUri,
          [
            uri,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromMediaId,
          [
            mediaId,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromSearch,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playFromUri(
    Uri? uri, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromUri,
          [
            uri,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playMediaItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #playMediaItem,
          [mediaItem],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> click([_i7.MediaButton? button = _i7.MediaButton.media]) =>
      (super.noSuchMethod(
        Invocation.method(
          #click,
          [button],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addQueueItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQueueItem,
          [mediaItem],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addQueueItems(List<_i7.MediaItem>? mediaItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQueueItems,
          [mediaItems],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> insertQueueItem(
    int? index,
    _i7.MediaItem? mediaItem,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertQueueItem,
          [
            index,
            mediaItem,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateQueue(List<_i7.MediaItem>? queue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQueue,
          [queue],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateMediaItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaItem,
          [mediaItem],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeQueueItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeQueueItem,
          [mediaItem],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> fastForward() => (super.noSuchMethod(
        Invocation.method(
          #fastForward,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> rewind() => (super.noSuchMethod(
        Invocation.method(
          #rewind,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> skipToQueueItem(int? index) => (super.noSuchMethod(
        Invocation.method(
          #skipToQueueItem,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setRating(
    _i7.Rating? rating, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRating,
          [
            rating,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setCaptioningEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setCaptioningEnabled,
          [enabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setShuffleMode(_i7.AudioServiceShuffleMode? shuffleMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShuffleMode,
          [shuffleMode],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seekBackward(bool? begin) => (super.noSuchMethod(
        Invocation.method(
          #seekBackward,
          [begin],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seekForward(bool? begin) => (super.noSuchMethod(
        Invocation.method(
          #seekForward,
          [begin],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<dynamic> customAction(
    String? name, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customAction,
          [
            name,
            extras,
          ],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<void> onTaskRemoved() => (super.noSuchMethod(
        Invocation.method(
          #onTaskRemoved,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> onNotificationDeleted() => (super.noSuchMethod(
        Invocation.method(
          #onNotificationDeleted,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i7.MediaItem>> getChildren(
    String? parentMediaId, [
    Map<String, dynamic>? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildren,
          [
            parentMediaId,
            options,
          ],
        ),
        returnValue: _i8.Future<List<_i7.MediaItem>>.value(<_i7.MediaItem>[]),
      ) as _i8.Future<List<_i7.MediaItem>>);

  @override
  _i4.ValueStream<Map<String, dynamic>> subscribeToChildren(
          String? parentMediaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToChildren,
          [parentMediaId],
        ),
        returnValue: _FakeValueStream_6<Map<String, dynamic>>(
          this,
          Invocation.method(
            #subscribeToChildren,
            [parentMediaId],
          ),
        ),
      ) as _i4.ValueStream<Map<String, dynamic>>);

  @override
  _i8.Future<_i7.MediaItem?> getMediaItem(String? mediaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaItem,
          [mediaId],
        ),
        returnValue: _i8.Future<_i7.MediaItem?>.value(),
      ) as _i8.Future<_i7.MediaItem?>);

  @override
  _i8.Future<List<_i7.MediaItem>> search(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i8.Future<List<_i7.MediaItem>>.value(<_i7.MediaItem>[]),
      ) as _i8.Future<List<_i7.MediaItem>>);

  @override
  _i8.Future<void> androidAdjustRemoteVolume(
          _i7.AndroidVolumeDirection? direction) =>
      (super.noSuchMethod(
        Invocation.method(
          #androidAdjustRemoteVolume,
          [direction],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> androidSetRemoteVolume(int? volumeIndex) =>
      (super.noSuchMethod(
        Invocation.method(
          #androidSetRemoteVolume,
          [volumeIndex],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i2.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.User get authUser => (super.noSuchMethod(
        Invocation.getter(#authUser),
        returnValue: _FakeUser_7(
          this,
          Invocation.getter(#authUser),
        ),
      ) as _i5.User);

  @override
  _i8.Future<_i2.TwoFactorChallenge?> login({
    required String? host,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #host: host,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i8.Future<_i2.TwoFactorChallenge?>.value(),
      ) as _i8.Future<_i2.TwoFactorChallenge?>);

  @override
  _i8.Future<void> completeTwoFactorChallenge({
    required String? loginToken,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTwoFactorChallenge,
          [],
          {
            #loginToken: loginToken,
            #code: code,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loginWithOneTimeToken({
    required String? host,
    required String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithOneTimeToken,
          [],
          {
            #host: host,
            #token: token,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void setAuthUser(_i5.User? user) => super.noSuchMethod(
        Invocation.method(
          #setAuthUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i5.User?> tryGetAuthUser() => (super.noSuchMethod(
        Invocation.method(
          #tryGetAuthUser,
          [],
        ),
        returnValue: _i8.Future<_i5.User?>.value(),
      ) as _i8.Future<_i5.User?>);

  @override
  _i8.Future<_i5.User> refreshAuthUser() => (super.noSuchMethod(
        Invocation.method(
          #refreshAuthUser,
          [],
        ),
        returnValue: _i8.Future<_i5.User>.value(_FakeUser_7(
          this,
          Invocation.method(
            #refreshAuthUser,
            [],
          ),
        )),
      ) as _i8.Future<_i5.User>);

  @override
  _i8.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i8.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DownloadProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadProvider extends _i1.Mock implements _i2.DownloadProvider {
  MockDownloadProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.Playable<dynamic>> get playables => (super.noSuchMethod(
        Invocation.getter(#playables),
        returnValue: <_i5.Playable<dynamic>>[],
      ) as List<_i5.Playable<dynamic>>);

  @override
  _i8.Stream<bool> get downloadsClearedStream => (super.noSuchMethod(
        Invocation.getter(#downloadsClearedStream),
        returnValue: _i8.Stream<bool>.empty(),
      ) as _i8.Stream<bool>);

  @override
  _i8.Stream<_i5.Playable<dynamic>> get downloadRemovedStream =>
      (super.noSuchMethod(
        Invocation.getter(#downloadRemovedStream),
        returnValue: _i8.Stream<_i5.Playable<dynamic>>.empty(),
      ) as _i8.Stream<_i5.Playable<dynamic>>);

  @override
  _i8.Stream<_i2.Download> get playableDownloadedStream => (super.noSuchMethod(
        Invocation.getter(#playableDownloadedStream),
        returnValue: _i8.Stream<_i2.Download>.empty(),
      ) as _i8.Stream<_i2.Download>);

  @override
  _i8.Future<String> get downloadsDir => (super.noSuchMethod(
        Invocation.getter(#downloadsDir),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.getter(#downloadsDir),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> download({required _i5.Playable<dynamic>? playable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [],
          {#playable: playable},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i2.Download? getForPlayable(_i5.Playable<dynamic>? playable) =>
      (super.noSuchMethod(Invocation.method(
        #getForPlayable,
        [playable],
      )) as _i2.Download?);

  @override
  bool has({required _i5.Playable<dynamic>? playable}) => (super.noSuchMethod(
        Invocation.method(
          #has,
          [],
          {#playable: playable},
        ),
        returnValue: false,
      ) as bool);

  @override
  void persistMetadata() => super.noSuchMethod(
        Invocation.method(
          #persistMetadata,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void persistMetadataIfNeeded(_i5.Playable<dynamic>? playable) =>
      super.noSuchMethod(
        Invocation.method(
          #persistMetadataIfNeeded,
          [playable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> removeForPlayable(_i5.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeForPlayable,
          [playable],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i8.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
